### ISSUE TITLE
kingt_tsai@hotmail.com

### ISSUE THREAD

**Issue by 8f82701** [tangqiaoboy/iOSBlogCN#24]
博客Title:FlyElephant
博客地址:http://www.cnblogs.com/xiaofeixiang/
RSS聚合地址:http://www.cnblogs.com/xiaofeixiang/
博主微博地址（选填）:http://weibo.com/2292565872/profile?topnav=1&wvr=6

**Comment by tangqiaoboy** [comment]
暂时打算再观察一下再决定是否收录。

**Comment by tangqiaoboy** [comment]
已经一年没更新了，不打算收录。
