### ISSUE TITLE
有一些博客已经失去了订阅连接了

### ISSUE THREAD

**Issue by honbolau** [tangqiaoboy/iOSBlogCN#26]
唐大大赶紧更新下
目前发现5个

**Comment by tangqiaoboy** [comment]
有可能作者已经没有维护了，我也无法一一更新。你可以把失去链接的博客地址给我，我先试着找一下。

**Comment by HectorLiuk** [comment]
http://blog.xcodev.com/atom.xml失效

**Comment by hbzs** [comment]
当前失效博客

- [言无不尽](http://tang3w.com/)
- [Chun Tips](http://chun.tips/)
