### ISSUE TITLE
你好，技术哥的博客, 经仔细Google,应该是失效了。

### ISSUE THREAD

**Issue by dengV** [tangqiaoboy/iOSBlogCN#36]
你好，技术哥的博客，	
http://suenblog.duapp.com/rss/，
经仔细Google,应该是失效了。
个人觉得：
可以更新，
可以后面加 Deprecated.

**Comment by tangqiaoboy** [comment]
已经更新，谢谢~

**Comment by dengV** [comment]
OK. 超喜欢你写的 烧脑体操
