### ISSUE TITLE
念茜的博客搬家了

### ISSUE THREAD

**Issue by ilawsonlu** [tangqiaoboy/iOSBlogCN#8]
http://nianxi.net 原来CSDN的已经停更了

**Comment by zyg-github** [comment]
http://nianxi.net 无法访问

**Comment by luckyfrank** [comment]
女神的博客不能访问呀，好伤心！

**Comment by tangqiaoboy** [comment]
是的，她没有维护了

**Comment by hstdt** [comment]
http://nianxi.net 上的四篇文章.如果要看的话,可以根据标题google   :(

![image](https://cloud.githubusercontent.com/assets/10215098/16142236/22614f84-3496-11e6-9b97-b6b8930c6e6b.png)

**Comment by colorfulOx** [comment]
那个nianxi的博客里面有一篇<Objective-C 的“多继承”>里面关于标准消息转发里面,someObj不知道是什么,是doctor的实例对象吗?
